"""nodal — 도메인 중립 그래프 엔진.

이 패키지는 torch 를 import 하지 않는다. 그래프 문서, 타입 시스템, 실행 루프만
안다. 이미지도 모델도 모른다 (AGENTS.md 아키텍처 절).

**상태**: M1 그래프 실행 엔진까지 구현되어 있다. 노드 확장 · lazy 입력 ·
`ExecutionBlocker`의 완전한 동작은 M5 범위다.

노드를 정의해서 실행하기까지의 경로는 `nodal.executor` 모듈 문서에 있다.
"""

from .assets import AssetRef, AssetStore, NullAssetStore
from .cache import (
    MISS,
    Cache,
    CachePolicy,
    LRUCache,
    NullCache,
    cache_key,
    graph_cache_keys,
)
from .errors import GraphIssue, GraphValidationError, IssueCode
from .events import (
    Cancelled,
    CancelToken,
    Event,
    EventSink,
    NodeCached,
    NodeContext,
    NodeDone,
    NodeError,
    NodePreview,
    NodeProgress,
    NodeStarted,
    NullEventSink,
    QueueStatus,
    RecordingEventSink,
    RunCancelled,
    RunDone,
    RunFailed,
    RunStarted,
)
from .executor import (
    Blocked,
    DynamicGraph,
    ExecutionBlocker,
    ExecutionList,
    Expanded,
    Failure,
    NeedsLazy,
    NodeExecutionError,
    NodeOutcome,
    PreparedGraph,
    RunResult,
    Success,
    TopologicalSort,
    execute,
    prepare_for_execution,
    propagate_blocker,
    resolve_inputs,
    run_node,
    validate_for_execution,
)
from .graph import (
    GRAPH_VERSION,
    LINK_KEY,
    PARAM_KEY,
    SUBGRAPH_TYPE_PREFIX,
    Graph,
    InputValue,
    Link,
    Node,
    NodeMeta,
    Param,
    ParamDef,
    SubgraphDef,
    check_graph,
    parse_graph,
    subgraph_name,
    validate_graph,
)
from .models import (
    CPU,
    DTYPES,
    Device,
    DeviceKind,
    DevicePlan,
    ModelLoadError,
    ModelStore,
    NullModelStore,
)
from .preview import (
    AssetPreview,
    EncodedPreview,
    InlinePreview,
    Preview,
    PreviewEncoder,
    PreviewEncoderNotFoundError,
    clear_preview_encoders,
    encode_preview,
    register_preview_encoder,
)
from .registry import (
    DuplicateNodeTypeError,
    NodeRegistry,
    NodeTypeNotFoundError,
    default_registry,
)
from .schema import (
    Bool,
    Combo,
    Float,
    InputDescriptor,
    InputSpec,
    Int,
    NodeResult,
    NodeSchema,
    OutputSpec,
    SchemaError,
    Seed,
    Socket,
    Str,
    combo_options,
    get_schema,
    node,
    output_names_for,
    reflect_node,
    register_combo_provider,
)
from .subgraph import MAX_DEPTH, MAX_NODES, FlattenResult, flatten
from .types import (
    BOOL,
    CLIP,
    FLOAT,
    INT,
    STRING,
    VAE,
    Any,
    AnyType,
    CatalogType,
    Conditioning,
    Image,
    Latent,
    ListType,
    Mask,
    Model,
    OpaqueType,
    PrimitiveType,
    Scheduler,
    TensorType,
    Type,
    TypeCatalog,
    TypeSpecError,
    UnionType,
    as_type,
    builtin,
    explain_incompatibility,
    is_compatible,
    load_catalog,
    parse_type_expr,
    type_names,
)

# 알파벳순 대신 모듈별로 묶는다. 이 목록은 M1 계약의 목차이고, 무엇이 구현됐고
# 무엇이 아직 시그니처뿐인지가 한눈에 보여야 한다.
#
# RUF022 를 끄는 이유: 이 규칙은 전역 알파벳 정렬을 요구해서 위 그룹 구분을
# 무너뜨린다 (`# --- 캐시` 아래에 `MISS` 하나만 남고 `Cache` 는 다른 그룹으로
# 흩어진다). M3 에서 그룹이 하나 늘자 규칙이 걸렸는데, 목차를 포기하는 것보다
# 규칙을 끄는 편이 낫다. 그룹 **안**은 정렬을 유지한다.
__all__ = [  # noqa: RUF022
    # --- 캐논 그래프 (구현됨)
    "GRAPH_VERSION",
    "LINK_KEY",
    "Graph",
    "GraphIssue",
    "GraphValidationError",
    "InputValue",
    "IssueCode",
    "Link",
    "Node",
    "NodeMeta",
    "check_graph",
    "parse_graph",
    "validate_graph",
    # --- 서브그래프 (M5.0 표현·검증 / M5.3 평탄화)
    "MAX_DEPTH",
    "MAX_NODES",
    "FlattenResult",
    "flatten",
    "PARAM_KEY",
    "SUBGRAPH_TYPE_PREFIX",
    "Param",
    "ParamDef",
    "SubgraphDef",
    "subgraph_name",
    # --- 타입 시스템 (구현됨, 규칙은 types.json)
    "BOOL",
    "CLIP",
    "FLOAT",
    "INT",
    "STRING",
    "VAE",
    "Any",
    "AnyType",
    "CatalogType",
    "Conditioning",
    "Image",
    "Latent",
    "ListType",
    "Mask",
    "Model",
    "OpaqueType",
    "PrimitiveType",
    "Scheduler",
    "TensorType",
    "Type",
    "TypeCatalog",
    "TypeSpecError",
    "UnionType",
    "as_type",
    "builtin",
    "explain_incompatibility",
    "is_compatible",
    "load_catalog",
    "parse_type_expr",
    "type_names",
    # --- 에셋 · 프리뷰 (M3 계약 — 인터페이스만, 구현은 server)
    "AssetPreview",
    "AssetRef",
    "AssetStore",
    "EncodedPreview",
    "InlinePreview",
    "NullAssetStore",
    "Preview",
    "PreviewEncoder",
    "PreviewEncoderNotFoundError",
    "clear_preview_encoders",
    "encode_preview",
    "register_preview_encoder",
    # --- 모델 · 디바이스 (M4 계약 — 인터페이스만, 구현은 nodes-diffusion)
    "CPU",
    "DTYPES",
    "Device",
    "DeviceKind",
    "DevicePlan",
    "ModelLoadError",
    "ModelStore",
    "NullModelStore",
    # --- 노드 스키마 (M1 계약)
    "Bool",
    "Combo",
    "Float",
    "InputDescriptor",
    "InputSpec",
    "Int",
    "NodeResult",
    "NodeSchema",
    "OutputSpec",
    "SchemaError",
    "Seed",
    "Socket",
    "Str",
    "combo_options",
    "get_schema",
    "node",
    "output_names_for",
    "reflect_node",
    "register_combo_provider",
    # --- 레지스트리 (M1 계약)
    "DuplicateNodeTypeError",
    "NodeRegistry",
    "NodeTypeNotFoundError",
    "default_registry",
    # --- 실행 엔진 (M1 계약)
    "Blocked",
    "DynamicGraph",
    "ExecutionBlocker",
    "ExecutionList",
    "Expanded",
    "Failure",
    "NeedsLazy",
    "NodeExecutionError",
    "NodeOutcome",
    "PreparedGraph",
    "RunResult",
    "Success",
    "TopologicalSort",
    "execute",
    "prepare_for_execution",
    "propagate_blocker",
    "resolve_inputs",
    "run_node",
    "validate_for_execution",
    # --- 캐시 (M1 계약)
    "MISS",
    "Cache",
    "CachePolicy",
    "LRUCache",
    "NullCache",
    "cache_key",
    "graph_cache_keys",
    # --- 이벤트와 취소 (M1 계약)
    "CancelToken",
    "Cancelled",
    "Event",
    "EventSink",
    "NodeCached",
    "NodeContext",
    "NodeDone",
    "NodeError",
    "NodePreview",
    "NodeProgress",
    "NodeStarted",
    "NullEventSink",
    "QueueStatus",
    "RecordingEventSink",
    "RunCancelled",
    "RunDone",
    "RunFailed",
    "RunStarted",
]

__version__ = "0.0.0"
