"""nodal — 도메인 중립 그래프 엔진.

이 패키지는 torch 를 import 하지 않는다. 그래프 문서, 타입 시스템, 실행 루프만
안다. 이미지도 모델도 모른다 (AGENTS.md 아키텍처 절).

**상태**: `graph` · `errors` · `types` 는 구현되어 있다. `schema` · `registry` ·
`executor` · `cache` · `events` 는 M1 계약(시그니처)이며 본문은 아직 없다 —
호출하면 `NotImplementedError` 가 난다.

노드를 정의해서 실행하기까지의 경로는 `nodal.executor` 모듈 문서에 있다.
"""

from .cache import (
    MISS,
    Cache,
    CachePolicy,
    LRUCache,
    NullCache,
    cache_key,
    graph_cache_keys,
)
from .errors import GraphIssue, GraphValidationError, IssueCode
from .events import (
    Cancelled,
    CancelToken,
    Event,
    EventSink,
    NodeCached,
    NodeContext,
    NodeDone,
    NodeError,
    NodePreview,
    NodeProgress,
    NodeStarted,
    NullEventSink,
    QueueStatus,
    RecordingEventSink,
    RunCancelled,
    RunDone,
    RunStarted,
)
from .executor import (
    Blocked,
    DynamicGraph,
    ExecutionBlocker,
    ExecutionList,
    Expanded,
    Failure,
    NeedsLazy,
    NodeExecutionError,
    NodeOutcome,
    RunResult,
    Success,
    TopologicalSort,
    execute,
    propagate_blocker,
    resolve_inputs,
    run_node,
    validate_for_execution,
)
from .graph import (
    GRAPH_VERSION,
    LINK_KEY,
    Graph,
    InputValue,
    Link,
    Node,
    NodeMeta,
    check_graph,
    parse_graph,
    validate_graph,
)
from .registry import (
    DuplicateNodeTypeError,
    NodeRegistry,
    NodeTypeNotFoundError,
    default_registry,
)
from .schema import (
    Bool,
    Combo,
    Float,
    InputDescriptor,
    InputSpec,
    Int,
    NodeResult,
    NodeSchema,
    OutputSpec,
    SchemaError,
    Socket,
    Str,
    get_schema,
    node,
    output_names_for,
    reflect_node,
)
from .types import (
    BOOL,
    CLIP,
    FLOAT,
    INT,
    STRING,
    VAE,
    Any,
    AnyType,
    Image,
    Latent,
    ListType,
    Mask,
    Model,
    OpaqueType,
    PrimitiveType,
    Scheduler,
    TensorType,
    Type,
    TypeCatalog,
    TypeSpecError,
    UnionType,
    builtin,
    explain_incompatibility,
    is_compatible,
    load_catalog,
    parse_type_expr,
    type_names,
)

# 알파벳순 대신 모듈별로 묶는다. 이 목록은 M1 계약의 목차이고, 무엇이 구현됐고
# 무엇이 아직 시그니처뿐인지가 한눈에 보여야 한다.
__all__ = [  # noqa: RUF022
    # --- 캐논 그래프 (구현됨)
    "GRAPH_VERSION",
    "LINK_KEY",
    "Graph",
    "GraphIssue",
    "GraphValidationError",
    "InputValue",
    "IssueCode",
    "Link",
    "Node",
    "NodeMeta",
    "check_graph",
    "parse_graph",
    "validate_graph",
    # --- 타입 시스템 (구현됨, 규칙은 types.json)
    "BOOL",
    "CLIP",
    "FLOAT",
    "INT",
    "STRING",
    "VAE",
    "Any",
    "AnyType",
    "Image",
    "Latent",
    "ListType",
    "Mask",
    "Model",
    "OpaqueType",
    "PrimitiveType",
    "Scheduler",
    "TensorType",
    "Type",
    "TypeCatalog",
    "TypeSpecError",
    "UnionType",
    "builtin",
    "explain_incompatibility",
    "is_compatible",
    "load_catalog",
    "parse_type_expr",
    "type_names",
    # --- 노드 스키마 (M1 계약)
    "Bool",
    "Combo",
    "Float",
    "InputDescriptor",
    "InputSpec",
    "Int",
    "NodeResult",
    "NodeSchema",
    "OutputSpec",
    "SchemaError",
    "Socket",
    "Str",
    "get_schema",
    "node",
    "output_names_for",
    "reflect_node",
    # --- 레지스트리 (M1 계약)
    "DuplicateNodeTypeError",
    "NodeRegistry",
    "NodeTypeNotFoundError",
    "default_registry",
    # --- 실행 엔진 (M1 계약)
    "Blocked",
    "DynamicGraph",
    "ExecutionBlocker",
    "ExecutionList",
    "Expanded",
    "Failure",
    "NeedsLazy",
    "NodeExecutionError",
    "NodeOutcome",
    "RunResult",
    "Success",
    "TopologicalSort",
    "execute",
    "propagate_blocker",
    "resolve_inputs",
    "run_node",
    "validate_for_execution",
    # --- 캐시 (M1 계약)
    "MISS",
    "Cache",
    "CachePolicy",
    "LRUCache",
    "NullCache",
    "cache_key",
    "graph_cache_keys",
    # --- 이벤트와 취소 (M1 계약)
    "CancelToken",
    "Cancelled",
    "Event",
    "EventSink",
    "NodeCached",
    "NodeContext",
    "NodeDone",
    "NodeError",
    "NodePreview",
    "NodeProgress",
    "NodeStarted",
    "NullEventSink",
    "QueueStatus",
    "RecordingEventSink",
    "RunCancelled",
    "RunDone",
    "RunStarted",
]

__version__ = "0.0.0"
