/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 입력 파일 업로드
         * @description content-addressed 로 저장한다. 같은 내용이면 같은 해시가 돌아온다.
         */
        post: operations["upload_asset_api_assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{asset_hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** content-addressed 조회 */
        get: operations["get_asset_api_assets__asset_hash__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extensions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 로드된 확장 · 실패한 확장
         * @description M6 까지는 빈 목록이 나간다. 실패한 확장을 숨기지 않는 것이 요점이다.
         */
        get: operations["list_extensions_api_extensions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/from-png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * PNG 에서 워크플로 복원
         * @description PNG 의 `nodal_workflow` iTXt 청크에서 캐논 그래프를 꺼낸다. 프론트의 드래그앤드롭이 이 엔드포인트로 파일을 던진다 — iTXt 파서를 Python·TS 양쪽에 두지 않기 위해서다.
         *
         *     청크가 없으면 404, PNG 로 읽을 수 없으면 400, 청크의 그래프가 무효하면 422 다.
         */
        post: operations["graph_from_png_api_graph_from_png_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 실행 없이 검증만
         * @description 구조 · 노드 타입 · 소켓 타입 호환성을 검사한다. **무효한 그래프도 200** 이다 — 검증은 질의이지 명령이 아니므로 `valid: false` 가 성공적인 답이다.
         */
        post: operations["validate_graph_endpoint_api_graph_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 전체 노드 스키마
         * @description 프론트 팔레트의 유일한 소스. 등록된 모든 노드의 입출력 소켓을 준다.
         */
        get: operations["list_nodes_api_nodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 큐와 히스토리 */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        /**
         * 실행 큐에 등록
         * @description 큐에 넣고 즉시 돌아온다. 진행 상황은 `/ws` 로 본다.
         *
         *     큐 진입 전에 전체 검증을 통과해야 한다 — 실패하면 422 와 `issues`.
         */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 상태와 결과 */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        /**
         * 취소
         * @description 협조적 취소를 요청한다. 이미 끝난 실행이면 그때의 상태가 그대로 돌아온다.
         */
        delete: operations["cancel_run_api_runs__run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssetInfo
         * @description `POST /api/assets` 의 응답. content-addressed 이므로 같은 파일은 같은 해시다.
         */
        AssetInfo: {
            /** Filename */
            filename?: string | null;
            /**
             * Hash
             * @description 내용 해시. `GET /api/assets/{hash}` 의 키
             */
            hash: string;
            /**
             * Height
             * @description 픽셀 높이. 이미지가 아니면 null
             */
            height?: number | null;
            /** Media Type */
            media_type: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Width
             * @description 픽셀 너비. 이미지가 아니면 null
             */
            width?: number | null;
        };
        /**
         * AssetPreviewModel
         * @description 저장소에 있는 프리뷰를 참조로 가리킨다 (노드의 최종 출력 이미지).
         */
        AssetPreviewModel: {
            asset: components["schemas"]["AssetRefModel"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "asset";
        };
        /**
         * AssetRefModel
         * @description `nodal.AssetRef` 의 전송 형태 — 저장소에 있는 값에 대한 참조 (M3).
         *
         *     `width` · `height` 가 참조에 들어 있는 이유는 프론트가 이미지를 **받기 전에**
         *     자리를 잡아야 하기 때문이다. 해시만 주면 GET 이 끝날 때까지 노드 레이아웃이
         *     튄다. 이미지가 아닌 에셋에서는 둘 다 `null` 이다.
         */
        AssetRefModel: {
            /**
             * Hash
             * @description 내용 해시. `GET /api/assets/{hash}` 의 키
             */
            hash: string;
            /**
             * Height
             * @description 픽셀 높이. 이미지가 아니면 null
             */
            height?: number | null;
            /**
             * Media Type
             * @description `image/png` 처럼
             */
            media_type: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Width
             * @description 픽셀 너비. 이미지가 아니면 null
             */
            width?: number | null;
        };
        /** Body_graph_from_png_api_graph_from_png_post */
        Body_graph_from_png_api_graph_from_png_post: {
            /**
             * File
             * @description `nodal_workflow` iTXt 청크를 담은 PNG
             */
            file: string;
        };
        /** Body_upload_asset_api_assets_post */
        Body_upload_asset_api_assets_post: {
            /**
             * File
             * @description 업로드할 파일
             */
            file: string;
        };
        /**
         * CancelRunResponse
         * @description `DELETE /api/runs/{id}` — 협조적 취소를 요청한다.
         *
         *     이미 끝난 실행이면 `cancelled` 가 아니라 그때의 상태가 그대로 돌아온다.
         */
        CancelRunResponse: {
            /** Run Id */
            run_id: string;
            status: components["schemas"]["RunStatus"];
        };
        /** CreateRunRequest */
        CreateRunRequest: {
            graph: components["schemas"]["Graph"];
            /**
             * Outputs
             * @description 실행할 출력 노드. 생략하면 그래프의 `outputs`
             */
            outputs?: string[] | null;
            /**
             * Priority
             * @description 클수록 먼저. 같으면 등록 순서
             * @default 0
             */
            priority: number;
            /**
             * Use Cache
             * @description 거짓이면 캐시를 무시하고 전부 재실행한다 (Ctrl+Shift+Enter)
             * @default true
             */
            use_cache: boolean;
        };
        /**
         * CreateRunResponse
         * @description `POST /api/runs` — 큐에 넣고 즉시 돌아온다. 진행은 `/ws` 로 본다.
         */
        CreateRunResponse: {
            /** Run Id */
            run_id: string;
            status: components["schemas"]["RunStatus"];
        };
        /** ErrorBody */
        ErrorBody: {
            /**
             * Code
             * @description `graph_invalid` · `run_not_found` · `node_failed` 등
             */
            code: string;
            /**
             * Issues
             * @description 문제를 전부 담는다. 첫 번째에서 멈추지 않는다
             */
            issues?: components["schemas"]["IssueModel"][];
            /** Message */
            message: string;
        };
        /**
         * ErrorResponse
         * @description 모든 4xx·5xx 응답의 본문. 상태 코드로 분기하고 본문은 항상 이 모양이다.
         */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /**
         * ExtensionInfo
         * @description 로드된, 또는 로드에 실패한 확장 하나 (design.md §8, M6).
         */
        ExtensionInfo: {
            /**
             * Error
             * @description 로드 실패 사유
             */
            error?: string | null;
            /** Id */
            id: string;
            /** Loaded */
            loaded: boolean;
            /** Name */
            name: string;
            /**
             * Nodal Api
             * @description 확장이 선언한 API 버전 범위
             */
            nodal_api: string;
            /**
             * Node Count
             * @default 0
             */
            node_count: number;
            /** Version */
            version: string;
        };
        /**
         * ExtensionsResponse
         * @description `GET /api/extensions` — 실패한 확장도 함께 보고한다.
         *
         *     확장 하나가 예외를 던져도 나머지는 로드된다. 실패는 숨기지 않고 UI 배너로
         *     올라간다 (design.md §8).
         */
        ExtensionsResponse: {
            /** Failed */
            failed?: components["schemas"]["ExtensionInfo"][];
            /** Loaded */
            loaded?: components["schemas"]["ExtensionInfo"][];
        };
        /**
         * Graph
         * @description 캐논 그래프 문서.
         *
         *     `ui` 는 프론트엔드 전용이다. 백엔드는 이 필드를 읽지 않으며, 없어도 완전히
         *     동작한다. 이 격리가 스키마 레벨에서 명시되는 것이 설계의 핵심이다.
         */
        Graph: {
            /**
             * Definitions
             * @description 서브그래프 정의 (M5, §5.5). 노드 타입 `subgraph.<이름>` 이 참조한다. 문서 안에 사는 이유는 문서 하나가 자기완결적이어야 하기 때문이다
             */
            definitions?: {
                [key: string]: components["schemas"]["SubgraphDef"];
            };
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /**
             * Nodal Version
             * @default 1
             * @constant
             */
            nodal_version: "1";
            /** Nodes */
            nodes?: {
                [key: string]: components["schemas"]["Node"];
            };
            /**
             * Outputs
             * @description 실행을 요청할 노드들. 여기서부터 역방향으로 조상만 수집된다.
             */
            outputs?: string[];
            /**
             * Ui
             * @description 프론트엔드 전용 상태. 백엔드는 읽지 않는다.
             */
            ui?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /**
         * GraphFromPngResponse
         * @description `POST /api/graph/from-png` 의 응답 (M3).
         *
         *     PNG 의 `nodal_workflow` iTXt 청크에서 캐논 그래프를 꺼낸 결과다.
         *     파싱을 서버 한 곳에만 두는 이유는 iTXt 파서가 Python·TS 양쪽에 생기면
         *     그것이 곧 "규칙을 두 번 쓰지 않는다" 위반이기 때문이다.
         *
         *     청크가 없거나 JSON 이 깨졌으면 이 응답이 아니라 `ErrorResponse` 가 나간다.
         */
        GraphFromPngResponse: {
            /** @description 복원된 캐논 그래프 */
            graph: components["schemas"]["Graph"];
            /**
             * Nodal Version
             * @description PNG 에 함께 박힌 `nodal_version` iTXt. 없으면 null
             */
            nodal_version?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InlinePreviewModel
         * @description 버려질 프리뷰를 data URI 로 그대로 싣는다 (샘플링 중간 프리뷰).
         */
        InlinePreviewModel: {
            /** Data Uri */
            data_uri: string;
            /**
             * Height
             * @default null
             */
            height: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "inline";
            /**
             * Width
             * @default null
             */
            width: number | null;
        };
        /**
         * InputSocketModel
         * @description 팔레트와 노드 본문이 그리는 입력 소켓 하나.
         */
        InputSocketModel: {
            default?: components["schemas"]["JsonValue"] | null;
            /**
             * Doc
             * @default
             */
            doc: string;
            /**
             * Lazy
             * @default false
             */
            lazy: boolean;
            /** Name */
            name: string;
            /** Required */
            required: boolean;
            /**
             * Type
             * @description `types.json` 의 타입 표현식
             */
            type: string | components["schemas"]["ListTypeExpr"] | components["schemas"]["UnionTypeExpr"] | components["schemas"]["OpaqueTypeExpr"] | components["schemas"]["TensorTypeExpr"];
            /**
             * Widget
             * @description min·max·step·options 등 위젯 힌트. 백엔드는 검증에만 쓴다
             */
            widget?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /**
         * IssueModel
         * @description `nodal.GraphIssue` 의 전송 형태. 필드 이름을 그대로 유지한다.
         *
         *     `location` 은 `nodes.<id>.inputs.<socket>` 경로다. 프론트는 이것만으로
         *     캔버스의 해당 소켓을 찾아 빨갛게 칠할 수 있다. 문제가 서브그래프 정의 안에
         *     있으면 `definitions.<이름>.` 이 앞에 붙는다 (M5).
         */
        IssueModel: {
            /**
             * Code
             * @description 안정적인 기계 판독용 코드 (`type_mismatch` 등)
             */
            code: string;
            /**
             * Definition
             * @description 문제가 서브그래프 정의 안에 있으면 그 정의 이름. `node_id` 만으로는 위치가 모호하다 — 정의마다 별개의 이름공간이라 ID 가 겹칠 수 있다
             */
            definition?: string | null;
            /**
             * Location
             * @description 캐논 문서 안의 경로. 그래프 전역이면 `graph`
             */
            location: string;
            /**
             * Message
             * @description 사람이 읽는 설명
             */
            message: string;
            /**
             * Node Id
             * @description 문제가 귀속되는 노드
             */
            node_id?: string | null;
            /**
             * Socket
             * @description 문제가 귀속되는 소켓
             */
            socket?: string | null;
        };
        JsonValue: unknown;
        /**
         * Link
         * @description 다른 노드의 출력 소켓에 대한 참조.
         *
         *     JSON에서는 ``{"$link": ["<node_id>", "<output_socket>"]}`` 로 표현된다.
         */
        Link: {
            /**
             * $Link
             * @description [출처 노드 ID, 출처 출력 소켓 이름]
             */
            $link: [
                string,
                string
            ];
        };
        /** ListTypeExpr */
        ListTypeExpr: {
            /** List */
            list: string | components["schemas"]["ListTypeExpr"] | components["schemas"]["UnionTypeExpr"] | components["schemas"]["OpaqueTypeExpr"] | components["schemas"]["TensorTypeExpr"];
        };
        /**
         * Node
         * @description 그래프의 노드 하나. ID는 그래프의 `nodes` 딕셔너리 키다.
         */
        Node: {
            /** Inputs */
            inputs?: {
                [key: string]: components["schemas"]["Link"] | components["schemas"]["Param"] | unknown;
            };
            meta?: components["schemas"]["NodeMeta"];
            /**
             * Type
             * @description 네임스페이스를 포함한 노드 타입 ID (예: image.Resize)
             */
            type: string;
        };
        /**
         * NodeMeta
         * @description 실행에 영향을 주지 않는 노드 부가 정보.
         */
        NodeMeta: {
            /** Notes */
            notes?: string | null;
            /** Title */
            title?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * NodeSchemaModel
         * @description `nodal.NodeSchema` 의 전송 형태.
         *
         *     입력·출력을 딕셔너리가 아니라 **리스트**로 보낸다. 선언 순서가 UI 의 소켓
         *     순서이고, 리스트가 그 순서를 잃지 않는 유일한 표현이다.
         */
        NodeSchemaModel: {
            /**
             * Aliases
             * @description 퍼지 검색용. 한글 포함
             */
            aliases?: string[];
            /** Cacheable */
            cacheable: boolean;
            /** Category */
            category: string;
            /**
             * Doc
             * @default
             */
            doc: string;
            /**
             * Id
             * @description 네임스페이스를 포함한 타입 ID. 캐논 그래프의 `node.type`
             */
            id: string;
            /** Inputs */
            inputs?: components["schemas"]["InputSocketModel"][];
            /** Output Node */
            output_node: boolean;
            /** Outputs */
            outputs?: components["schemas"]["OutputSocketModel"][];
            /** Title */
            title: string;
            /** Version */
            version: string;
        };
        /**
         * NodesResponse
         * @description `GET /api/nodes` — 프론트 팔레트의 유일한 소스.
         */
        NodesResponse: {
            /** Nodes */
            nodes: components["schemas"]["NodeSchemaModel"][];
            /**
             * Types Version
             * @description `types.json` 의 `types_version`. 프론트가 로드한 타입 규칙과 대조한다
             */
            types_version: string;
        };
        /** OpaqueTypeExpr */
        OpaqueTypeExpr: {
            /**
             * Capabilities
             * @description 능력 태그
             */
            capabilities?: string[];
            /**
             * Opaque
             * @description 핸들 이름 (`Model`, `VAE` ...)
             */
            opaque: string;
        };
        /**
         * OutputRefModel
         * @description `nodal.OutputRef` 의 전송 형태 — 값이 아니라 **참조**다 (design.md §6).
         *
         *     이미지나 텐서를 그대로 실으면 메가바이트가 나간다. 작은 값만 `inline` 에
         *     싣고 큰 값은 `asset` 참조로 가리킨다.
         */
        OutputRefModel: {
            /** @description 저장소에 있는 값의 참조 (M3). M2 까지는 해시 문자열이었다 */
            asset?: components["schemas"]["AssetRefModel"] | null;
            /** @description JSON 으로 표현되는 작은 값 */
            inline?: components["schemas"]["JsonValue"] | null;
            /** Socket */
            socket: string;
            /** Type */
            type: string | components["schemas"]["ListTypeExpr"] | components["schemas"]["UnionTypeExpr"] | components["schemas"]["OpaqueTypeExpr"] | components["schemas"]["TensorTypeExpr"];
        };
        /** OutputSocketModel */
        OutputSocketModel: {
            /**
             * Doc
             * @default
             */
            doc: string;
            /** Name */
            name: string;
            /** Type */
            type: string | components["schemas"]["ListTypeExpr"] | components["schemas"]["UnionTypeExpr"] | components["schemas"]["OpaqueTypeExpr"] | components["schemas"]["TensorTypeExpr"];
        };
        /**
         * Param
         * @description 서브그래프 **정의 안에서** 그 정의의 파라미터를 가리키는 참조.
         *
         *     JSON에서는 ``{"$param": "<이름>"}`` 로 표현된다.
         *
         *     정의 밖에서는 의미가 없다. 최상위 그래프의 입력 슬롯에 나타나면 검증이
         *     거부한다 (`PARAM_OUTSIDE_DEFINITION`) — 조용히 리터럴 딕셔너리로 취급하면
         *     실행 시점에 정체불명의 값이 노드로 들어간다.
         */
        Param: {
            /**
             * $Param
             * @description 이 정의의 `params` 에 선언된 파라미터 이름
             */
            $param: string;
        };
        /**
         * ParamDef
         * @description 서브그래프 파라미터 하나의 선언 — 인스턴스가 채우는 구멍이다.
         *
         *     MCP 툴 `run_template_<템플릿 ID>` 가 받는 파라미터가 정확히 이 목록이다.
         *     이 선언에서 툴의 `inputSchema` 가 기계적으로 생성된다 (docs/design.md §12.3).
         *
         *     `default` 가 **없거나 `null`** 이면 필수 파라미터다. 둘을 구분하지 않는 이유는
         *     캐논 문서에 빈 값이 두 가지 생기면 안 되기 때문이고, 카탈로그 타입 중 `null`
         *     을 정상 값으로 갖는 것이 없어 잃는 것이 없기 때문이다.
         */
        ParamDef: {
            /** @description 기본값. 없거나 null 이면 필수 파라미터다 */
            default?: components["schemas"]["JsonValue"];
            /** @description `types.json` 의 타입 표현식. 문자열(`"INT"`)이거나 구조화 형태(`{"list": "Image"}`)다 */
            type: components["schemas"]["JsonValue"];
            /**
             * Widget
             * @description 위젯 힌트 (min·max·options 등). 열린 딕셔너리이고 실행은 읽지 않는다
             */
            widget?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /**
         * RunDetail
         * @description `GET /api/runs/{id}` — 상태와 결과.
         *
         *     `executed` 와 `cached` 를 나눠 두는 것이 요점이다. WS 를 놓친 클라이언트도
         *     무엇이 재실행되고 무엇이 캐시였는지 알 수 있다 (design.md §6).
         */
        RunDetail: {
            /**
             * Blocked
             * @description 블로커로 막힌 노드 (M5)
             */
            blocked?: string[];
            /**
             * Cached
             * @description 캐시 히트로 건너뛴 노드
             */
            cached?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Elapsed Ms */
            elapsed_ms?: number | null;
            /** @description `status` 가 `failed` 일 때만 채워진다 */
            error?: components["schemas"]["ErrorBody"] | null;
            /**
             * Executed
             * @description 실제로 실행된 노드
             */
            executed?: string[];
            /** Finished At */
            finished_at?: string | null;
            /**
             * Outputs
             * @description 출력 노드 ID → 그 노드의 출력 참조들
             */
            outputs?: {
                [key: string]: components["schemas"]["OutputRefModel"][];
            };
            /** Run Id */
            run_id: string;
            /** Started At */
            started_at?: string | null;
            status: components["schemas"]["RunStatus"];
        };
        /**
         * RunListResponse
         * @description `GET /api/runs` — 큐와 히스토리.
         */
        RunListResponse: {
            /**
             * History
             * @description 최근 완료분. 최신이 먼저
             */
            history?: components["schemas"]["RunSummary"][];
            /**
             * Limit
             * @description 히스토리 보관 상한
             */
            limit: number;
            /** Queued */
            queued?: components["schemas"]["RunSummary"][];
            running?: components["schemas"]["RunSummary"] | null;
        };
        /**
         * RunStatus
         * @description 실행 상태. 프론트가 이 값으로 화면을 분기한다.
         * @enum {string}
         */
        RunStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /**
         * RunSummary
         * @description 큐·히스토리 목록용 경량 표현. 출력값을 담지 않는다.
         */
        RunSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Elapsed Ms */
            elapsed_ms?: number | null;
            /** Finished At */
            finished_at?: string | null;
            /** Node Count */
            node_count: number;
            /** Run Id */
            run_id: string;
            /** Started At */
            started_at?: string | null;
            status: components["schemas"]["RunStatus"];
        };
        /**
         * SubgraphDef
         * @description 재사용 가능한 워크플로 조각. **MCP 툴의 단위**다 (design.md §12.2).
         *
         *     정의는 캐논 문서 **안에** 산다. 외부 파일 참조가 아니다 — 문서 하나가 그대로
         *     재현 가능한 레시피여야 PNG `iTXt` 워크플로 복원(§6)이 성립하기 때문이다.
         *
         *     경계는 두 방향으로 뚫린다:
         *
         *     - **들어오는 값**은 `params` 로 선언하고 정의 안에서 `{"$param": ...}` 로 쓴다
         *     - **나가는 값**은 `returns` 가 정의 안의 (노드, 소켓)에 이름을 붙인 것이다.
         *       인스턴스를 소비하는 링크 `{"$link": ["<인스턴스>", "<이름>"]}` 가 이 이름을
         *       가리키고, 평탄화가 그것을 안쪽 노드로 재배선한다 (§5.5)
         *
         *     `Graph.outputs` 가 아니라 `returns` 인 이유: 그쪽은 **실행을 요청할 노드
         *     목록**이고 이쪽은 **노출할 소켓**이다. 한 문서 안에서 한 단계 차이로 나란히
         *     놓이는 두 필드가 같은 단어면 반드시 헷갈린다. 노드 SDK 가 같은 역할을 이미
         *     `returns` 로 부른다는 점도 맞물린다 — 인스턴스는 밖에서 보면 노드다.
         */
        SubgraphDef: {
            /**
             * Nodes
             * @description 정의 안의 노드. 최상위 그래프와 **별개의 이름공간**이다
             */
            nodes?: {
                [key: string]: components["schemas"]["Node"];
            };
            /**
             * Params
             * @description 이 정의가 받는 파라미터. 인스턴스의 입력 소켓이 된다
             */
            params?: {
                [key: string]: components["schemas"]["ParamDef"];
            };
            /**
             * Returns
             * @description 인스턴스가 내보내는 출력 소켓 이름 → 정의 안의 (노드, 소켓). `Graph.outputs`(실행 요청 노드 목록)와 다른 것이라 이름도 다르다
             */
            returns?: {
                [key: string]: components["schemas"]["Link"];
            };
        };
        /** TensorBodyExpr */
        TensorBodyExpr: {
            /** Dtypes */
            dtypes: string[];
            /**
             * Shape
             * @description 정수는 고정 크기, 문자열 라벨과 null 은 임의 크기
             */
            shape: (number | string | null)[];
        };
        /** TensorTypeExpr */
        TensorTypeExpr: {
            tensor: components["schemas"]["TensorBodyExpr"];
        };
        /** UnionTypeExpr */
        UnionTypeExpr: {
            /** Union */
            union: (string | components["schemas"]["ListTypeExpr"] | components["schemas"]["UnionTypeExpr"] | components["schemas"]["OpaqueTypeExpr"] | components["schemas"]["TensorTypeExpr"])[];
        };
        /** ValidateRequest */
        ValidateRequest: {
            /** @description 캐논 그래프 문서 그대로. 서버는 변환하지 않는다 */
            graph: components["schemas"]["Graph"];
            /**
             * Outputs
             * @description 검증할 출력 노드. 생략하면 그래프의 `outputs`
             */
            outputs?: string[] | null;
        };
        /**
         * ValidateResponse
         * @description `POST /api/graph/validate` — 실행 없이 검증만 한다.
         *
         *     무효한 그래프도 **200** 이다. 검증은 질의이지 명령이 아니므로, "이 그래프는
         *     무효다"는 성공적인 답이다. 4xx 는 요청 자체가 잘못됐을 때만 나간다.
         */
        ValidateResponse: {
            /** Issues */
            issues?: components["schemas"]["IssueModel"][];
            /** Valid */
            valid: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        WsEvent: components["schemas"]["WsRunStarted"] | components["schemas"]["WsNodeStarted"] | components["schemas"]["WsNodeProgress"] | components["schemas"]["WsNodePreview"] | components["schemas"]["WsNodeCached"] | components["schemas"]["WsNodeDone"] | components["schemas"]["WsNodeError"] | components["schemas"]["WsRunDone"] | components["schemas"]["WsRunFailed"] | components["schemas"]["WsRunCancelled"] | components["schemas"]["WsQueueStatus"];
        /** WsNodeCached */
        WsNodeCached: {
            /** Node Id */
            node_id: string;
            /** Run Id */
            run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            t: "node.cached";
        };
        /** WsNodeDone */
        WsNodeDone: {
            /** Node Id */
            node_id: string;
            /** Outputs */
            outputs?: components["schemas"]["OutputRefModel"][];
            /** Run Id */
            run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            t: "node.done";
        };
        /** WsNodeError */
        WsNodeError: {
            /** Message */
            message: string;
            /** Node Id */
            node_id: string;
            /** Run Id */
            run_id: string;
            /**
             * Socket
             * @default null
             */
            socket: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            t: "node.error";
            /** Traceback */
            traceback?: string[];
        };
        /** WsNodePreview */
        WsNodePreview: {
            /** Node Id */
            node_id: string;
            /** Preview */
            preview: components["schemas"]["InlinePreviewModel"] | components["schemas"]["AssetPreviewModel"];
            /** Run Id */
            run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            t: "node.preview";
        };
        /** WsNodeProgress */
        WsNodeProgress: {
            /** Node Id */
            node_id: string;
            /** Run Id */
            run_id: string;
            /** Step */
            step: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            t: "node.progress";
            /** Total */
            total: number;
        };
        /** WsNodeStarted */
        WsNodeStarted: {
            /** Node Id */
            node_id: string;
            /** Run Id */
            run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            t: "node.started";
        };
        /** WsQueueStatus */
        WsQueueStatus: {
            /** Pending */
            pending: number;
            /**
             * Running
             * @default null
             */
            running: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            t: "queue";
        };
        /** WsRunCancelled */
        WsRunCancelled: {
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Run Id */
            run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            t: "run.cancelled";
        };
        /** WsRunDone */
        WsRunDone: {
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Run Id */
            run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            t: "run.done";
        };
        /**
         * WsRunFailed
         * @description 실행이 실패했다. `run.done`·`run.cancelled` 와 대칭인 종료 이벤트다.
         *
         *     `node.error` 만으로는 부족하다 — 사이클처럼 어느 노드에도 귀속되지 않는
         *     실패가 있고, 그때 사유를 아는 통로가 여기뿐이다.
         */
        WsRunFailed: {
            /**
             * Code
             * @description `node_failed` · `graph_invalid` · `internal_error`
             */
            code: string;
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Message */
            message: string;
            /** Run Id */
            run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            t: "run.failed";
        };
        /** WsRunStarted */
        WsRunStarted: {
            /** Node Count */
            node_count: number;
            /** Run Id */
            run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            t: "run.started";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_asset_api_assets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_asset_api_assets_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetInfo"];
                };
            };
            /** @description 요청이 잘못됐다 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 대상이 없다 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 그래프 검증 실패. `issues` 가 어느 노드·어느 소켓인지 지목한다 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 계약은 확정됐지만 아직 구현되지 않았다 (M3) */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_asset_api_assets__asset_hash__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 내용 해시 */
                asset_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 파일 내용 그대로. `Content-Type` 은 업로드 시 판별된 것 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description 요청이 잘못됐다 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 대상이 없다 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 그래프 검증 실패. `issues` 가 어느 노드·어느 소켓인지 지목한다 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 계약은 확정됐지만 아직 구현되지 않았다 (M3) */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_extensions_api_extensions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtensionsResponse"];
                };
            };
        };
    };
    graph_from_png_api_graph_from_png_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_graph_from_png_api_graph_from_png_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphFromPngResponse"];
                };
            };
            /** @description 요청이 잘못됐다 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 대상이 없다 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 그래프 검증 실패. `issues` 가 어느 노드·어느 소켓인지 지목한다 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 계약은 확정됐지만 아직 구현되지 않았다 (M3) */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    validate_graph_endpoint_api_graph_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateResponse"];
                };
            };
            /** @description 요청이 잘못됐다 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 대상이 없다 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 그래프 검증 실패. `issues` 가 어느 노드·어느 소켓인지 지목한다 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 계약은 확정됐지만 아직 구현되지 않았다 (M3) */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_nodes_api_nodes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodesResponse"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                /** @description 히스토리 최대 개수 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRunResponse"];
                };
            };
            /** @description 요청이 잘못됐다 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 대상이 없다 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 그래프 검증 실패. `issues` 가 어느 노드·어느 소켓인지 지목한다 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 계약은 확정됐지만 아직 구현되지 않았다 (M3) */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 실행 ID */
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description 요청이 잘못됐다 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 대상이 없다 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 그래프 검증 실패. `issues` 가 어느 노드·어느 소켓인지 지목한다 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 계약은 확정됐지만 아직 구현되지 않았다 (M3) */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cancel_run_api_runs__run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 실행 ID */
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelRunResponse"];
                };
            };
            /** @description 요청이 잘못됐다 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 대상이 없다 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 그래프 검증 실패. `issues` 가 어느 노드·어느 소켓인지 지목한다 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 계약은 확정됐지만 아직 구현되지 않았다 (M3) */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
