/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 입력 파일 업로드
         * @description content-addressed 로 저장한다. 같은 내용이면 같은 해시가 돌아온다.
         */
        post: operations["upload_asset_api_assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{asset_hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** content-addressed 조회 */
        get: operations["get_asset_api_assets__asset_hash__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extensions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 로드된 확장 · 실패한 확장
         * @description M6 까지는 빈 목록이 나간다. 실패한 확장을 숨기지 않는 것이 요점이다.
         */
        get: operations["list_extensions_api_extensions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 실행 없이 검증만
         * @description 구조 · 노드 타입 · 소켓 타입 호환성을 검사한다. **무효한 그래프도 200** 이다 — 검증은 질의이지 명령이 아니므로 `valid: false` 가 성공적인 답이다.
         */
        post: operations["validate_graph_endpoint_api_graph_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 발견된 모델 목록
         * @description M4 까지는 빈 목록이 나간다. 형태만 먼저 고정한다.
         */
        get: operations["list_models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 전체 노드 스키마
         * @description 프론트 팔레트의 유일한 소스. 등록된 모든 노드의 입출력 소켓을 준다.
         */
        get: operations["list_nodes_api_nodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 큐와 히스토리 */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        /**
         * 실행 큐에 등록
         * @description 큐에 넣고 즉시 돌아온다. 진행 상황은 `/ws` 로 본다.
         *
         *     큐 진입 전에 전체 검증을 통과해야 한다 — 실패하면 422 와 `issues`.
         */
        post: operations["create_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 상태와 결과 */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        /**
         * 취소
         * @description 협조적 취소를 요청한다. 이미 끝난 실행이면 그때의 상태가 그대로 돌아온다.
         */
        delete: operations["cancel_run_api_runs__run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssetInfo
         * @description `POST /api/assets` 의 응답. content-addressed 이므로 같은 파일은 같은 해시다.
         */
        AssetInfo: {
            /** Filename */
            filename?: string | null;
            /**
             * Hash
             * @description 내용 해시. `GET /api/assets/{hash}` 의 키
             */
            hash: string;
            /** Media Type */
            media_type: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** Body_upload_asset_api_assets_post */
        Body_upload_asset_api_assets_post: {
            /**
             * File
             * @description 업로드할 파일
             */
            file: string;
        };
        /**
         * CancelRunResponse
         * @description `DELETE /api/runs/{id}` — 협조적 취소를 요청한다.
         *
         *     이미 끝난 실행이면 `cancelled` 가 아니라 그때의 상태가 그대로 돌아온다.
         */
        CancelRunResponse: {
            /** Run Id */
            run_id: string;
            status: components["schemas"]["RunStatus"];
        };
        /** CreateRunRequest */
        CreateRunRequest: {
            graph: components["schemas"]["Graph"];
            /**
             * Outputs
             * @description 실행할 출력 노드. 생략하면 그래프의 `outputs`
             */
            outputs?: string[] | null;
            /**
             * Priority
             * @description 클수록 먼저. 같으면 등록 순서
             * @default 0
             */
            priority: number;
            /**
             * Use Cache
             * @description 거짓이면 캐시를 무시하고 전부 재실행한다 (Ctrl+Shift+Enter)
             * @default true
             */
            use_cache: boolean;
        };
        /**
         * CreateRunResponse
         * @description `POST /api/runs` — 큐에 넣고 즉시 돌아온다. 진행은 `/ws` 로 본다.
         */
        CreateRunResponse: {
            /** Run Id */
            run_id: string;
            status: components["schemas"]["RunStatus"];
        };
        /** ErrorBody */
        ErrorBody: {
            /**
             * Code
             * @description `graph_invalid` · `run_not_found` · `node_failed` 등
             */
            code: string;
            /**
             * Issues
             * @description 문제를 전부 담는다. 첫 번째에서 멈추지 않는다
             */
            issues?: components["schemas"]["IssueModel"][];
            /** Message */
            message: string;
        };
        /**
         * ErrorResponse
         * @description 모든 4xx·5xx 응답의 본문. 상태 코드로 분기하고 본문은 항상 이 모양이다.
         */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /**
         * ExtensionInfo
         * @description 로드된, 또는 로드에 실패한 확장 하나 (design.md §8, M6).
         */
        ExtensionInfo: {
            /**
             * Error
             * @description 로드 실패 사유
             */
            error?: string | null;
            /** Id */
            id: string;
            /** Loaded */
            loaded: boolean;
            /** Name */
            name: string;
            /**
             * Nodal Api
             * @description 확장이 선언한 API 버전 범위
             */
            nodal_api: string;
            /**
             * Node Count
             * @default 0
             */
            node_count: number;
            /** Version */
            version: string;
        };
        /**
         * ExtensionsResponse
         * @description `GET /api/extensions` — 실패한 확장도 함께 보고한다.
         *
         *     확장 하나가 예외를 던져도 나머지는 로드된다. 실패는 숨기지 않고 UI 배너로
         *     올라간다 (design.md §8).
         */
        ExtensionsResponse: {
            /** Failed */
            failed?: components["schemas"]["ExtensionInfo"][];
            /** Loaded */
            loaded?: components["schemas"]["ExtensionInfo"][];
        };
        /**
         * Graph
         * @description 캐논 그래프 문서.
         *
         *     `ui` 는 프론트엔드 전용이다. 백엔드는 이 필드를 읽지 않으며, 없어도 완전히
         *     동작한다. 이 격리가 스키마 레벨에서 명시되는 것이 설계의 핵심이다.
         */
        Graph: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /**
             * Nodal Version
             * @default 1
             * @constant
             */
            nodal_version: "1";
            /** Nodes */
            nodes?: {
                [key: string]: components["schemas"]["Node"];
            };
            /**
             * Outputs
             * @description 실행을 요청할 노드들. 여기서부터 역방향으로 조상만 수집된다.
             */
            outputs?: string[];
            /**
             * Ui
             * @description 프론트엔드 전용 상태. 백엔드는 읽지 않는다.
             */
            ui?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InputSocketModel
         * @description 팔레트와 노드 본문이 그리는 입력 소켓 하나.
         */
        InputSocketModel: {
            default?: components["schemas"]["JsonValue"] | null;
            /**
             * Doc
             * @default
             */
            doc: string;
            /**
             * Lazy
             * @default false
             */
            lazy: boolean;
            /** Name */
            name: string;
            /** Required */
            required: boolean;
            /**
             * Type
             * @description `types.json` 카탈로그 표기 (`INT`, `Image`, `List[Image]`)
             */
            type: string;
            /**
             * Widget
             * @description min·max·step·options 등 위젯 힌트. 백엔드는 검증에만 쓴다
             */
            widget?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /**
         * IssueModel
         * @description `nodal.GraphIssue` 의 전송 형태. 필드 이름을 그대로 유지한다.
         *
         *     `location` 은 `nodes.<id>.inputs.<socket>` 경로다. 프론트는 이것만으로
         *     캔버스의 해당 소켓을 찾아 빨갛게 칠할 수 있다.
         */
        IssueModel: {
            /**
             * Code
             * @description 안정적인 기계 판독용 코드 (`type_mismatch` 등)
             */
            code: string;
            /**
             * Location
             * @description 캐논 문서 안의 경로. 그래프 전역이면 `graph`
             */
            location: string;
            /**
             * Message
             * @description 사람이 읽는 설명
             */
            message: string;
            /**
             * Node Id
             * @description 문제가 귀속되는 노드
             */
            node_id?: string | null;
            /**
             * Socket
             * @description 문제가 귀속되는 소켓
             */
            socket?: string | null;
        };
        JsonValue: unknown;
        /**
         * Link
         * @description 다른 노드의 출력 소켓에 대한 참조.
         *
         *     JSON에서는 ``{"$link": ["<node_id>", "<output_socket>"]}`` 로 표현된다.
         */
        Link: {
            /**
             * $Link
             * @description [출처 노드 ID, 출처 출력 소켓 이름]
             */
            $link: [
                string,
                string
            ];
        };
        /**
         * ModelEntry
         * @description 발견된 모델 파일 하나. M4 에서 채워진다.
         */
        ModelEntry: {
            /**
             * Kind
             * @description `checkpoints` · `loras` · `vae` 등 디렉토리 종류
             */
            kind: string;
            /** Modified At */
            modified_at?: string | null;
            /** Name */
            name: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /**
         * ModelsResponse
         * @description `GET /api/models` — M4 까지는 비어 있다. 형태만 먼저 고정한다.
         */
        ModelsResponse: {
            /**
             * Kinds
             * @description 스캔 대상 종류
             */
            kinds?: string[];
            /** Models */
            models?: components["schemas"]["ModelEntry"][];
        };
        /**
         * Node
         * @description 그래프의 노드 하나. ID는 그래프의 `nodes` 딕셔너리 키다.
         */
        Node: {
            /** Inputs */
            inputs?: {
                [key: string]: components["schemas"]["Link"] | unknown;
            };
            meta?: components["schemas"]["NodeMeta"];
            /**
             * Type
             * @description 네임스페이스를 포함한 노드 타입 ID (예: image.Resize)
             */
            type: string;
        };
        /**
         * NodeMeta
         * @description 실행에 영향을 주지 않는 노드 부가 정보.
         */
        NodeMeta: {
            /** Notes */
            notes?: string | null;
            /** Title */
            title?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * NodeSchemaModel
         * @description `nodal.NodeSchema` 의 전송 형태.
         *
         *     입력·출력을 딕셔너리가 아니라 **리스트**로 보낸다. 선언 순서가 UI 의 소켓
         *     순서이고, 리스트가 그 순서를 잃지 않는 유일한 표현이다.
         */
        NodeSchemaModel: {
            /**
             * Aliases
             * @description 퍼지 검색용. 한글 포함
             */
            aliases?: string[];
            /** Cacheable */
            cacheable: boolean;
            /** Category */
            category: string;
            /**
             * Doc
             * @default
             */
            doc: string;
            /**
             * Id
             * @description 네임스페이스를 포함한 타입 ID. 캐논 그래프의 `node.type`
             */
            id: string;
            /** Inputs */
            inputs?: components["schemas"]["InputSocketModel"][];
            /** Output Node */
            output_node: boolean;
            /** Outputs */
            outputs?: components["schemas"]["OutputSocketModel"][];
            /** Title */
            title: string;
            /** Version */
            version: string;
        };
        /**
         * NodesResponse
         * @description `GET /api/nodes` — 프론트 팔레트의 유일한 소스.
         */
        NodesResponse: {
            /** Nodes */
            nodes: components["schemas"]["NodeSchemaModel"][];
            /**
             * Types Version
             * @description `types.json` 의 `types_version`. 프론트가 로드한 타입 규칙과 대조한다
             */
            types_version: string;
        };
        /**
         * OutputRefModel
         * @description `nodal.OutputRef` 의 전송 형태 — 값이 아니라 **참조**다 (design.md §6).
         *
         *     이미지나 텐서를 그대로 실으면 메가바이트가 나간다. 작은 값만 `inline` 에
         *     싣고 큰 값은 `asset` 해시로 가리킨다.
         */
        OutputRefModel: {
            /**
             * Asset
             * @description content-addressed 해시. `GET /api/assets/{hash}` 로 받는다 (M3)
             */
            asset?: string | null;
            /** @description JSON 으로 표현되는 작은 값 */
            inline?: components["schemas"]["JsonValue"] | null;
            /** Socket */
            socket: string;
            /** Type */
            type: string;
        };
        /** OutputSocketModel */
        OutputSocketModel: {
            /**
             * Doc
             * @default
             */
            doc: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
        };
        /**
         * RunDetail
         * @description `GET /api/runs/{id}` — 상태와 결과.
         *
         *     `executed` 와 `cached` 를 나눠 두는 것이 요점이다. WS 를 놓친 클라이언트도
         *     무엇이 재실행되고 무엇이 캐시였는지 알 수 있다 (design.md §6).
         */
        RunDetail: {
            /**
             * Blocked
             * @description 블로커로 막힌 노드 (M5)
             */
            blocked?: string[];
            /**
             * Cached
             * @description 캐시 히트로 건너뛴 노드
             */
            cached?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Elapsed Ms */
            elapsed_ms?: number | null;
            /** @description `status` 가 `failed` 일 때만 채워진다 */
            error?: components["schemas"]["ErrorBody"] | null;
            /**
             * Executed
             * @description 실제로 실행된 노드
             */
            executed?: string[];
            /** Finished At */
            finished_at?: string | null;
            /**
             * Outputs
             * @description 출력 노드 ID → 그 노드의 출력 참조들
             */
            outputs?: {
                [key: string]: components["schemas"]["OutputRefModel"][];
            };
            /** Run Id */
            run_id: string;
            /** Started At */
            started_at?: string | null;
            status: components["schemas"]["RunStatus"];
        };
        /**
         * RunListResponse
         * @description `GET /api/runs` — 큐와 히스토리.
         */
        RunListResponse: {
            /**
             * History
             * @description 최근 완료분. 최신이 먼저
             */
            history?: components["schemas"]["RunSummary"][];
            /**
             * Limit
             * @description 히스토리 보관 상한
             */
            limit: number;
            /** Queued */
            queued?: components["schemas"]["RunSummary"][];
            running?: components["schemas"]["RunSummary"] | null;
        };
        /**
         * RunStatus
         * @description 실행 상태. 프론트가 이 값으로 화면을 분기한다.
         * @enum {string}
         */
        RunStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /**
         * RunSummary
         * @description 큐·히스토리 목록용 경량 표현. 출력값을 담지 않는다.
         */
        RunSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Elapsed Ms */
            elapsed_ms?: number | null;
            /** Finished At */
            finished_at?: string | null;
            /** Node Count */
            node_count: number;
            /** Run Id */
            run_id: string;
            /** Started At */
            started_at?: string | null;
            status: components["schemas"]["RunStatus"];
        };
        /** ValidateRequest */
        ValidateRequest: {
            /** @description 캐논 그래프 문서 그대로. 서버는 변환하지 않는다 */
            graph: components["schemas"]["Graph"];
            /**
             * Outputs
             * @description 검증할 출력 노드. 생략하면 그래프의 `outputs`
             */
            outputs?: string[] | null;
        };
        /**
         * ValidateResponse
         * @description `POST /api/graph/validate` — 실행 없이 검증만 한다.
         *
         *     무효한 그래프도 **200** 이다. 검증은 질의이지 명령이 아니므로, "이 그래프는
         *     무효다"는 성공적인 답이다. 4xx 는 요청 자체가 잘못됐을 때만 나간다.
         */
        ValidateResponse: {
            /** Issues */
            issues?: components["schemas"]["IssueModel"][];
            /** Valid */
            valid: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        WsEvent: components["schemas"]["WsRunStarted"] | components["schemas"]["WsNodeStarted"] | components["schemas"]["WsNodeProgress"] | components["schemas"]["WsNodePreview"] | components["schemas"]["WsNodeCached"] | components["schemas"]["WsNodeDone"] | components["schemas"]["WsNodeError"] | components["schemas"]["WsRunDone"] | components["schemas"]["WsRunCancelled"] | components["schemas"]["WsQueueStatus"];
        /** WsNodeCached */
        WsNodeCached: {
            /** Node Id */
            node_id: string;
            /** Run Id */
            run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            t: "node.cached";
        };
        /** WsNodeDone */
        WsNodeDone: {
            /** Node Id */
            node_id: string;
            /** Outputs */
            outputs?: components["schemas"]["OutputRefModel"][];
            /** Run Id */
            run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            t: "node.done";
        };
        /** WsNodeError */
        WsNodeError: {
            /** Message */
            message: string;
            /** Node Id */
            node_id: string;
            /** Run Id */
            run_id: string;
            /**
             * Socket
             * @default null
             */
            socket: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            t: "node.error";
            /** Traceback */
            traceback?: string[];
        };
        /** WsNodePreview */
        WsNodePreview: {
            /**
             * Image
             * @description base64 데이터 URI 이거나 에셋 해시
             */
            image: string;
            /** Node Id */
            node_id: string;
            /** Run Id */
            run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            t: "node.preview";
        };
        /** WsNodeProgress */
        WsNodeProgress: {
            /** Node Id */
            node_id: string;
            /** Run Id */
            run_id: string;
            /** Step */
            step: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            t: "node.progress";
            /** Total */
            total: number;
        };
        /** WsNodeStarted */
        WsNodeStarted: {
            /** Node Id */
            node_id: string;
            /** Run Id */
            run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            t: "node.started";
        };
        /** WsQueueStatus */
        WsQueueStatus: {
            /** Pending */
            pending: number;
            /**
             * Running
             * @default null
             */
            running: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            t: "queue";
        };
        /** WsRunCancelled */
        WsRunCancelled: {
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Run Id */
            run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            t: "run.cancelled";
        };
        /** WsRunDone */
        WsRunDone: {
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Run Id */
            run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            t: "run.done";
        };
        /** WsRunStarted */
        WsRunStarted: {
            /** Node Count */
            node_count: number;
            /** Run Id */
            run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            t: "run.started";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_asset_api_assets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_asset_api_assets_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetInfo"];
                };
            };
            /** @description 요청이 잘못됐다 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 대상이 없다 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 그래프 검증 실패. `issues` 가 어느 노드·어느 소켓인지 지목한다 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_asset_api_assets__asset_hash__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 내용 해시 */
                asset_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 파일 내용 그대로. `Content-Type` 은 업로드 시 판별된 것 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description 요청이 잘못됐다 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 대상이 없다 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 그래프 검증 실패. `issues` 가 어느 노드·어느 소켓인지 지목한다 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_extensions_api_extensions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtensionsResponse"];
                };
            };
        };
    };
    validate_graph_endpoint_api_graph_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateResponse"];
                };
            };
            /** @description 요청이 잘못됐다 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 대상이 없다 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 그래프 검증 실패. `issues` 가 어느 노드·어느 소켓인지 지목한다 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsResponse"];
                };
            };
        };
    };
    list_nodes_api_nodes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodesResponse"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                /** @description 히스토리 최대 개수 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRunResponse"];
                };
            };
            /** @description 요청이 잘못됐다 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 대상이 없다 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 그래프 검증 실패. `issues` 가 어느 노드·어느 소켓인지 지목한다 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 실행 ID */
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description 요청이 잘못됐다 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 대상이 없다 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 그래프 검증 실패. `issues` 가 어느 노드·어느 소켓인지 지목한다 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cancel_run_api_runs__run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 실행 ID */
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelRunResponse"];
                };
            };
            /** @description 요청이 잘못됐다 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 대상이 없다 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 그래프 검증 실패. `issues` 가 어느 노드·어느 소켓인지 지목한다 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
